api/urls.py
from django.conf.urls import url
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [
	url(r'^mywall/$', views.WallList.as_view(), name='wall'),
	url(r'^fellowship/(?P<action>[a-zA-Z]+)/(?P<username>[a-zA-Z]+)/$', views.FollowingApi.as_view(), name='following'),
	url(r'^favouring/(?P<action>[a-zA-Z]+)/(?P<post_id>[0-9]+)/$', views.FavourPost.as_view(), name='favouring'),
	url(r'^replywall/$', views.ReplyWallpost.as_view(), name='replywallpost'),
	url(r'^editpost/(?P<post_id>[0-9]+)/$', views.Editpost.as_view(), name='editpost'),
	url(r'^commentpost/$', views.Commentpost.as_view(), name='commentpost'),
	url(r'^addpost/$', views.Addpost.as_view(), name='addtpost'),
	url(r'^likepage/(?P<username>[a-zA-Z]+)/$', views.LikePage.as_view(), name='likepage'),
	url(r'^checknotification/$', views.Checknotification.as_view(), name='checknotification'),
	url(r'^contact/$', views.Contact.as_view(), name='contact'),
	url(r'^searchUsername/$', views.SearchUsername.as_view(), name='searchusername'),
	url(r'^searchPost/$', views.SearchPost.as_view(), name='searchpost'),
	url(r'^createEvent/$', views.CreateEvent.as_view(), name='createEvent'),
	url(r'^deleteEvent/(?P<id>[0-9]+)/$', views.DeleteEvent.as_view(), name='deleteEvent'),
	url(r'^viewallevents/$', views.AllEvent.as_view(), name='allevent'),
	url(r'^addtodotask/$', views.AddTodoTask.as_view(), name='addtodotask'),
	url(r'^deltodotask/(?P<id>[0-9]+)/$', views.DeleteTodoTask.as_view(), name='deltodotask'),
	url(r'^checktodotask/(?P<id>[0-9]+)/$', views.CheckTodoTask.as_view(), name='checktodotask'),
	url(r'^gettasks/(?P<id>[0-9]+)/$', views.GetTasks.as_view(), name='gettasks'),
	url(r'^edittask/(?P<id>[0-9]+)/$', views.EditTasks.as_view(), name='edittasks'),
	url(r'^deletepost/(?P<id>[0-9]+)/$', views.DeletePost.as_view(), name='deletepost'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

post/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.posts, name='posts'),

	# Listing all post of postType=type
	url(r'^(?P<postType>[a-zA-Z]+)/all/$', views.posts, name='myposts'),

	# Getting a single post with id=post_id
	url(r'^(?P<post_id>[0-9]+)/$', views.a_post, name='one_post'),
]

index/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
	profilePics = models.FileField()
	aboutUser = models.TextField()
	numofnewnote = models.IntegerField(default=0)

	def __str__(self):
		return self.username
# 

from post.models import Post

class Following(models.Model):
	member = models.CharField(max_length=500, default='Anonymous')
	follow = models.ForeignKey(User, on_delete=models.CASCADE)
	date = models.DateTimeField(auto_now=True)

	def __str__(self):
		return (self.follow)


class View(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	post = models.ForeignKey(Post, on_delete=models.CASCADE)

	
class Wall(models.Model):
	user = models.CharField(max_length=500)
	writer = models.ForeignKey(User, on_delete=models.CASCADE)
	body = models.TextField()
	date = models.DateTimeField(auto_now=True)

class WallReply(models.Model):
	wall = models.ForeignKey(Wall, on_delete=models.CASCADE)
	body = models.CharField(max_length=500)
	writer = models.ForeignKey(User, on_delete=models.CASCADE)
	date = models.DateTimeField(auto_now=True)


class Favour(models.Model):
	favouredBy = models.ForeignKey(User, on_delete=models.CASCADE)
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	date = models.DateTimeField(auto_now=True)


class Notification(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	message = models.CharField(max_length=500)
	url = models.URLField(max_length=10000, default='/post')
	img = models.CharField(max_length=500, default='create.jpg')
	date = models.DateTimeField(auto_now=True)


class Likepage(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	fan = models.CharField(max_length=500) # username of the person that like your page
	date = models.DateTimeField(auto_now=True)

class Contact(models.Model):
	subject = models.CharField(max_length=1000)
	sender = models.CharField(max_length=500)
	email = models.CharField(max_length=500)
	message = models.TextField()
	date = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.sender

class Quoteoftheday(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE)

	def __str__(self):
		return self.post.title


class Jokeoftheday(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE)

	def __str__(self):
		return self.post.title



class Motivationoftheday(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE)

	def __str__(self):
		return self.post.title


class Oneofakind(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE)

	def __str__(self):
		return self.post.title


class Selectionoftheday(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE)

	def __str__(self):
		return self.post.title

class Event(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=500)
	date = models.DateTimeField(auto_now=True)

class Todotask(models.Model):
	event = models.ForeignKey(Event, on_delete=models.CASCADE)
	task = models.CharField(max_length=1000)
	done = models.BooleanField(default=False)

post/models.py
from django.db import models
from index.models import User

# Create your models here.


class Post(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=250, default='Not set')
	body = models.TextField()
	postType = models.CharField(max_length=100)
	category = models.CharField(max_length=100)
	edited = models.BooleanField(default=False)
	background = models.CharField(max_length=1000, default='na2.jpg')
	date = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.title+'-'+self.postType

class Postcomment(models.Model):
	targetpost = models.ForeignKey(Post, on_delete=models.CASCADE)
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	body = models.CharField(max_length=500)
	date = models.DateTimeField(auto_now=True)

post/forms.py
from django import forms
from .models import Post, Postcomment

class EditPost(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'body', 'category', 'postType']

class CommentPost(forms.ModelForm):

    class Meta:
        model = Postcomment
        fields = ['body']

class CreateNewPost(forms.ModelForm):

	class Meta:
		model = Post
		fields = ['title', 'body', 'postType', 'category']

post/views.py
from django.shortcuts import render, redirect
from post.models import Post, Postcomment
from .forms import EditPost, CommentPost, CreateNewPost
from index.models import User, Favour, Following, View, Notification
from django.contrib import messages

# Create your views here.

def posts(request, postType):
	if not request.user.is_authenticated:
		messages.error(request, 'Ensure you are logged in or create an account now.')
		return redirect('/sign-in')
	else:
		user = User.objects.get(username=request.user.username)
		following = []
		for followMem in Following.objects.filter(member=request.user.username):
			following.append(followMem.follow.username)

		if Post.objects.filter(postType=postType):
			return render(request, 'post/posts.html', {
				'title': 'List of '+postType,
				'posts': Post.objects.filter(postType=postType).order_by('-date'),
				'postType': postType,
				'authentication': True,
				'user': user,
				'following': following,
				'notification': Notification.objects.filter(user=User.objects.get(username=request.user.username)).order_by('-date')[:4]
			})
		else:
			messages.error(request, 'The post type is incorrect')
			return redirect('/')

def a_post(request, post_id):
	if not request.user.is_authenticated:
		messages.error(request, 'Ensure you are logged in or create an account now.')
		return redirect('/sign-in')
	else:
		""" This reture the post with id of post_id """
		user = User.objects.filter(username=request.user.username)[0]
		post = Post.objects.filter(pk=post_id)[0]
		viewed = View.objects.filter(user=user, post=post)
		if not viewed:
			newview = View(user=user, post=post)
			newview.save()

		user = User.objects.get(username=request.user.username)

		following = []
		for followMem in Following.objects.filter(member=request.user.username):
			following.append(followMem.follow.username)
		return render(request, 'post/single.html', {
			'title': post.title+' by '+post.user.username,
			'post': post,
			'authentication': True,
			'following': following,
			'user': user,
			'notification': Notification.objects.filter(user=User.objects.get(username=request.user.username)).order_by('-date')[:4]
		})

# def givecomment(request, post_id):
# 	if not request.user.is_authenticated:
# 		messages.error(request, 'Ensure you are logged in or create an account now.')
# 		return redirect('/sign-in')
# 	else:
# 		user = User.objects.filter(username=request.user.username)[0]
# 		post = Post.objects.filter(pk=post_id)[0]

# 		viewed = View.objects.filter(user=user, post=post)
# 		viewed = View.objects.filter(user=user, post=post)
		
# 		if not viewed:
# 			newview = View(user=user, post=post)
# 			newview.save()

# 		form = CommentPost(request.POST)
# 		if form.is_valid():
# 			comment = Postcomment()
# 			comment.targetpost = post
# 			comment.author = User.objects.get(username=request.user.username)
# 			comment.body = form.cleaned_data['body']
# 			comment.save()

# 			# Ensuring the post author doesn't get a note when he give a comment
# 			if request.user.username != Post.objects.get(pk=post_id).user.username:
# 				# Creating Notification for the author of the post commented on.
# 				newNotification = Notification()
# 				newNotification.user = Post.objects.get(pk=post_id).user
# 				newNotification.message = request.user.username+' commented on your post named '+Post.objects.get(pk=post_id).title
# 				newNotification.url = '/post/'+str(post_id)
# 				newNotification.img = 'comment.png'
# 				newNotification.save()

# 				alert = newNotification.user
# 				alert.numofnewnote += 1;
# 				alert.save()

# 			# list to ensure no repetition of note to one commentator.
# 			givento = []
# 			for commentator in Postcomment.objects.filter(targetpost=Post.objects.get(pk=post_id)):
# 				# Ensuring the owner of post doesn't get a notification because they also commented
# 				if commentator.author.username != Post.objects.get(pk=post_id).user.username:
# 					# Ensuring the new commentator doesn't get a note if he has given a comment before.
# 					if request.user.username != commentator.author.username:
						
# 						if commentator.author.username not in givento:
# 							newNotification = Notification()
# 							newNotification.user = commentator.author
# 							newNotification.message = request.user.username+' gave a comment on '+Post.objects.get(pk=post_id).title+' you are following'
# 							newNotification.url = '/post/'+str(post_id)
# 							newNotification.img = 'comment.png'
# 							newNotification.save()

# 							alert = newNotification.user
# 							alert.numofnewnote += 1;
# 							alert.save()

# 							givento.append(commentator.author.username)

# 			return redirect('/profile')
# 		else:
# 			messages.success(request, 'Please the field before submitting.')
# 			return redirect('/profile')

post/templates/post/posts.html
{% extends "index/base.html" %}


{% load static %}

{% block content %}
<!--================Header Menu Area =================-->
<style type="text/css">
    .authordetails{
        min-height: 360px;
        margin-bottom: 140px;
        background: white;
    }
    .postdetail{
        min-height: 350px;
    }
    .makeblack{
        color: black;
    }
</style>

<!--================Blog Categorie Area =================-->
<section class="blog_categorie_area">
<div class="container">
    <div class="row">
        <div class="col-lg-4">
            <div class="categories_post">
                <img src="{% static '/img/blog/cat-post/cat-post-3.jpg' %}" alt="post">
                <div class="categories_details">
                    <div class="categories_text">
                        <a href="/post/Joke/all"><h5>Social Life</h5></a>
                        <div class="border_line"></div>
                        <p>Enjoy your social life together</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="categories_post">
                <img src="{% static '/img/blog/cat-post/cat-post-2.jpg' %}" alt="post">
                <div class="categories_details">
                    <div class="categories_text">
                        <a href="/post/Puzzle/all"><h5>Puzzles</h5></a>
                        <div class="border_line"></div>
                        <p>Hack the world</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="categories_post">
                <img src="{% static '/img/blog/cat-post/cat-post-1.jpg' %}" alt="post">
                <div class="categories_details">
                    <div class="categories_text">
                        <a href="/post/Motivation/all"><h5>Motivation</h5></a>
                        <div class="border_line"></div>
                        <p>Stay motivated and energized</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</section>
<!--================Blog Categorie Area =================-->

<!--================Blog Area =================-->
<section class="blog_area">
<div class="container">
    <template id="postSearchResultTemplate">
        <li>
            {% verbatim %}
            <img src="/static/index/img/background/{{background}}" class="searchImg">
            <a href="/post/{{id}}">{{title}}</a>
            <span class="searchResultPostNum">By <a href="/profile/{{author}}">{{author}}</a></span>
            {% endverbatim %}
        </li>
    </template>
    <form class="postSearch" onsubmit="return false;">
        <input type="text" class="form-control" placeholder="Search Posts by title">
        <p class="hide">{{csrf_token}}</p>

        <div class="postSearchResult">
            <ul>
            </ul>
       </div>
    </form>
    <br>
    <h2>House of {{postType}}s</h2>
    <div class="row">
        <div class="col-lg-8">
            <div class="blog_left_sidebar">
                {% if posts %}
                    {% for post in posts %}
                        <article class="row blog_item postdetail">
                           <div class="col-md-3">
                               <div class="blog_info text-right">
                                    <div class="post_tag">
                                        <a href="/post/{{post.pk}}">{{post.category}}</a>
                                    </div>
                                    <ul class="blog_meta list">
                                        <li><a href="/profile/{{post.user.username}}">{{post.user.username}}<i class="lnr lnr-user"></i></a></li>
                                        <li><a href="/post/{{post.pk}}">{{post.date|date:"d M, Y"}}<i class="lnr lnr-calendar-full"></i></a></li>
                                        <li><a href="/post/{{post.pk}}">{{post.view_set.count}} Views<i class="lnr lnr-eye"></i></a></li>
                                        <li><a href="/post/{{post.pk}}">{{post.postcomment_set.count}} Comments<i class="lnr lnr-bubble"></i></a></li>
                                    </ul>
                                    <h3 class="media-body">
                                        <a href="#fav" class="icon_btn makeblack" title="Add to favourite list"><i class="lnr lnr lnr-diamond favouring"  data-action="favour" data-postid="{{post.pk}}"></i></a>
                                    </h3>
                                </div>
                           </div>
                            <div class="col-md-9">
                                <div class="blog_post">
                                    <img src="/static/img/background/{{post.background}}" alt="">
                                    <div class="blog_details">
                                        <a href="/post/{{post.pk}}"><h2>{{post.title}}</h2></a>
                                        <p>{{ post.body | truncatewords:19 }}</p>
                                        <a href="/post/{{post.pk}}" class="white_bg_btn">View More</a>
                                    </div>
                                </div>
                            </div>
                        </article>
                    {% endfor %}
                    <!-- <nav class="blog-pagination justify-content-center d-flex">
                        <ul class="pagination">
                            <li class="page-item">
                                <a href="#" class="page-link" aria-label="Previous">
                                    <span aria-hidden="true">
                                        <span class="lnr lnr-chevron-left"></span>
                                    </span>
                                </a>
                            </li>
                            
                            <li class="page-item"><a href="#" class="page-link">01</a></li>
                            <li class="page-item active"><a href="#" class="page-link">02</a></li>
                            <li class="page-item"><a href="#" class="page-link">03</a></li>
                            <li class="page-item"><a href="#" class="page-link">04</a></li>
                            <li class="page-item"><a href="#" class="page-link">09</a></li>
                            <li class="page-item">
                                <a href="#" class="page-link" aria-label="Next">
                                    <span aria-hidden="true">
                                        <span class="lnr lnr-chevron-right"></span>
                                    </span>
                                </a>
                            </li>
                        </ul>
                    </nav> -->
                {% else %}
                    <p>No {{postType}} to display</p>
                {% endif %}
            </div>
        </div>
        <div class="col-lg-4">
            <div class="blog_right_sidebar">
                {% if posts %}
                <!-- Each author for every post -->
                    {% for author in posts %}
                        <aside class="single_sidebar_widget author_widget authordetails">
                            {% if author.user.profilePics %}
                                <img class="author_img rounded-circle post_profpics" src="{{author.user.profilePics.url}}" alt="">
                            {% else %}
                                <img class="author_img rounded-circle post_profpics" src="{% static 'index/media/default.png' %}" alt="">
                            {% endif %}
                            <a href="/profile/{{author.user.username}}"><h4>{{author.user.username}}</h4></a>
                            <p>{{author.user.post_set.count}} Posts</p>

                        
                            <!-- Description of the author from author's profile -->
                            {% if author.user.aboutUser %}
                                <p>{{author.user.aboutUser | truncatewords:19}}</p>
                            {% else %}
                                <p>No description about {{author.user.ursername}} yet.</p>
                            {% endif %}
                            {% if user.username != author.user.username %}
                                <div class="media-body">
                                    {% if author.user.username in following %}
                                        <a href="#u" data-action="unfollow" class="white_bg_btn fellowship {{author.user.username}}" data-username={{author.user.username}}>Unfollow</a>
                                    {% else %}
                                        <a href="#u" data-action="follow" class="white_bg_btn fellowship {{author.user.username}}" data-username={{author.user.username}}>Follow</a>
                                    {% endif %}
                                </div>
                            {% endif %}
                            <div class="br"></div>
                        </aside>
                    {% endfor %}
                {% endif %}
                <!-- <aside class="single_sidebar_widget popular_post_widget">
                    <h3 class="widget_title">Popular Posts</h3>
                    <div class="media post_item">
                        <img src="{% static '/img/blog/popular-post/post1.jpg' %}" alt="post">
                        <div class="media-body">
                            <a href="blog-details.html"><h3>Space The Final Frontier</h3></a>
                            <p>02 Hours ago</p>
                        </div>
                    </div>
                    <div class="media post_item">
                        <img src="{% static '/img/blog/popular-post/post2.jpg' %}" alt="post">
                        <div class="media-body">
                            <a href="blog-details.html"><h3>The Amazing Hubble</h3></a>
                            <p>02 Hours ago</p>
                        </div>
                    </div>
                    <div class="media post_item">
                        <img src="{% static '/img/blog/popular-post/post3.jpg' %}" alt="post">
                        <div class="media-body">
                            <a href="blog-details.html"><h3>Astronomy Or Astrology</h3></a>
                            <p>03 Hours ago</p>
                        </div>
                    </div>
                    <div class="media post_item">
                        <img src="{% static '/img/blog/popular-post/post4.jpg' %}" alt="post">
                        <div class="media-body">
                            <a href="blog-details.html"><h3>Asteroids telescope</h3></a>
                            <p>01 Hours ago</p>
                        </div>
                    </div>
                    <div class="br"></div>
                </aside> -->
                <aside class="single_sidebar_widget ads_widget">
                    <a href="#"><img class="img-fluid" src="{% static '/img/blog/add.jpg' %}" alt=""></a>
                    <div class="br"></div>
                </aside>
                
            </div>
        </div>
    </div>
</div>
</section>
<!--================Blog Area =================-->
{% endblock %}
<!--================ End footer Area  =================-->