api/urls.py
from django.conf.urls import url
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [
	url(r'^mywall/$', views.WallList.as_view(), name='wall'),
	url(r'^fellowship/(?P<action>[a-zA-Z]+)/(?P<username>[a-zA-Z]+)/$', views.FollowingApi.as_view(), name='following'),
	url(r'^favouring/(?P<action>[a-zA-Z]+)/(?P<post_id>[0-9]+)/$', views.FavourPost.as_view(), name='favouring'),
	url(r'^replywall/$', views.ReplyWallpost.as_view(), name='replywallpost'),
	url(r'^editpost/(?P<post_id>[0-9]+)/$', views.Editpost.as_view(), name='editpost'),
	url(r'^commentpost/$', views.Commentpost.as_view(), name='commentpost'),
	url(r'^addpost/$', views.Addpost.as_view(), name='addtpost'),
	url(r'^likepage/(?P<username>[a-zA-Z]+)/$', views.LikePage.as_view(), name='likepage'),
	url(r'^checknotification/$', views.Checknotification.as_view(), name='checknotification'),
	url(r'^contact/$', views.Contact.as_view(), name='contact'),
	url(r'^searchUsername/$', views.SearchUsername.as_view(), name='searchusername'),
	url(r'^searchPost/$', views.SearchPost.as_view(), name='searchpost'),
	url(r'^createEvent/$', views.CreateEvent.as_view(), name='createEvent'),
	url(r'^deleteEvent/(?P<id>[0-9]+)/$', views.DeleteEvent.as_view(), name='deleteEvent'),
	url(r'^viewallevents/$', views.AllEvent.as_view(), name='allevent'),
	url(r'^addtodotask/$', views.AddTodoTask.as_view(), name='addtodotask'),
	url(r'^deltodotask/(?P<id>[0-9]+)/$', views.DeleteTodoTask.as_view(), name='deltodotask'),
	url(r'^checktodotask/(?P<id>[0-9]+)/$', views.CheckTodoTask.as_view(), name='checktodotask'),
	url(r'^gettasks/(?P<id>[0-9]+)/$', views.GetTasks.as_view(), name='gettasks'),
	url(r'^edittask/(?P<id>[0-9]+)/$', views.EditTasks.as_view(), name='edittasks'),
	url(r'^deletepost/(?P<id>[0-9]+)/$', views.DeletePost.as_view(), name='deletepost'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

index/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
	profilePics = models.FileField()
	aboutUser = models.TextField()
	numofnewnote = models.IntegerField(default=0)

	def __str__(self):
		return self.username
# 

from post.models import Post

class Following(models.Model):
	member = models.CharField(max_length=500, default='Anonymous')
	follow = models.ForeignKey(User, on_delete=models.CASCADE)
	date = models.DateTimeField(auto_now=True)

	def __str__(self):
		return (self.follow)


class View(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	post = models.ForeignKey(Post, on_delete=models.CASCADE)

	
class Wall(models.Model):
	user = models.CharField(max_length=500)
	writer = models.ForeignKey(User, on_delete=models.CASCADE)
	body = models.TextField()
	date = models.DateTimeField(auto_now=True)

class WallReply(models.Model):
	wall = models.ForeignKey(Wall, on_delete=models.CASCADE)
	body = models.CharField(max_length=500)
	writer = models.ForeignKey(User, on_delete=models.CASCADE)
	date = models.DateTimeField(auto_now=True)


class Favour(models.Model):
	favouredBy = models.ForeignKey(User, on_delete=models.CASCADE)
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	date = models.DateTimeField(auto_now=True)


class Notification(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	message = models.CharField(max_length=500)
	url = models.URLField(max_length=10000, default='/post')
	img = models.CharField(max_length=500, default='create.jpg')
	date = models.DateTimeField(auto_now=True)


class Likepage(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	fan = models.CharField(max_length=500) # username of the person that like your page
	date = models.DateTimeField(auto_now=True)

class Contact(models.Model):
	subject = models.CharField(max_length=1000)
	sender = models.CharField(max_length=500)
	email = models.CharField(max_length=500)
	message = models.TextField()
	date = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.sender

class Quoteoftheday(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE)

	def __str__(self):
		return self.post.title


class Jokeoftheday(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE)

	def __str__(self):
		return self.post.title



class Motivationoftheday(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE)

	def __str__(self):
		return self.post.title


class Oneofakind(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE)

	def __str__(self):
		return self.post.title


class Selectionoftheday(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE)

	def __str__(self):
		return self.post.title

class Event(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=500)
	date = models.DateTimeField(auto_now=True)

class Todotask(models.Model):
	event = models.ForeignKey(Event, on_delete=models.CASCADE)
	task = models.CharField(max_length=1000)
	done = models.BooleanField(default=False)

index/templates/index/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{{ title }}</title>
	{% load static %}

	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="{% static 'index/css/adminstyle.css' %}"> -->
    <link rel="stylesheet" href="{% static '/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static '/vendors/linericon/style.css' %}">
    <link rel="stylesheet" href="{% static '/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static '/vendors/owl-carousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static '/vendors/lightbox/simpleLightbox.css' %}">
    <link rel="stylesheet" href="{% static '/vendors/nice-select/css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static '/vendors/animate-css/animate.css' %}">
    <link rel="stylesheet" href="{% static '/vendors/jquery-ui/jquery-ui.css' %}"> 
   	<link href="{% static 'index/img/favicon.ico' %}" rel="icon" type="image/x-icon">

    <!-- main css -->

    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'index/css/responsive.css' %}">

    <!-- Dac css -->
    <link rel="stylesheet" type="text/css" href="{% static 'index/css/dac.css' %}">
    

    <style type="text/css">
		body{
			background: url('{% static '/img/background.png' %}');
		}
	</style>

</head>
<body class="body">
	<!-- Heart break code -->
	<!-- <span class="fa-stack fa-3x">
	    <i class="fa fa-heart fa-stack-1x"></i>
	    <i class="fa fa-bolt fa-stack-1x fa-inverse"></i>
	</span> -->

	<!--================Header Menu Area =================-->
    <header class="header_area">
       	<div class="top_menu row m0">
       		<div class="container">
				<div class="float-left">
					<a href="mailto:ganiuibrahim3000@gmail.com">ganiuibrahim3000@gmail.com</a>
					<a href="/">Welcome to Flick</a>
				</div>
				<!-- <div class="float-right">
					<ul class="header_social">
						<li><a href="#"><i class="fa fa-facebook"></i></a></li>
						<li><a href="#"><i class="fa fa-twitter"></i></a></li>
						<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
						<li><a href="#"><i class="fa fa-behance"></i></a></li>
					</ul>
				</div> -->
       		</div>	
       	</div>	
        <div class="main_menu">
        	<nav class="navbar navbar-expand-lg navbar-light main_box">
				<div class="container">
					<!-- Brand and toggle get grouped for better mobile display -->
					<a class="navbar-brand logo_h" href="/"><img src="{% static 'index/img/logo.png' %}" alt=""></a>
					<template id="searchResultTemplate">
                   		<li>
                   			{% verbatim %}
                   			<img src="{{profilePics}}" class="searchImg">
                   			<a href="/profile/{{username}}">{{username}}</a>
                   			<span class="searchResultPostNum">{{noOfPost}} Post</span>
                   			{% endverbatim %}
                   		</li>
               		</template>
					{% if request.user.is_authenticated %}
						<form class="searchForm hide" onsubmit="return false;">
	                        <input type="text" class="form-control" style="width: 100%;" placeholder="Search username" id="searchText">
	                        <p class="hide" id="searchToken">{{csrf_token}}</p>
	                       <div class="searchResult hide">
	                       		<ul>
			                    </ul>
	                       </div>
	                    </form>
                    {% endif %}
					<!-- <span class="navbar-brand logo_h site_logo">Flense</span> -->
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse offset" id="navbarSupportedContent">
						{% if authentication %}
							<ul class="nav navbar-nav menu_nav ml-auto">
								<li class="nav-item"><a class="nav-link {% if loc == 'home'  %} 'active' {% endif %}" href="/">HOME</a></li>
								<li class="nav-item"><a class="nav-link profile" href="/profile">PROFILE</a></li> 
								<li class="nav-item submenu dropdown">
									<a href="#" class="nav-link dropdown-toggle pages" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">PAGES</a>
									<ul class="dropdown-menu">
										<li class="nav-item"><a class="nav-link" href="/post/Joke/all">Jokes</a>
										<li class="nav-item"><a class="nav-link" href="/post/Quote/all">Quotes</a>
										<li class="nav-item"><a class="nav-link" href="/post/Motivation/all">Motivation</a>
										<li class="nav-item"><a class="nav-link" href="/post/Puzzle/all">Puzzle</a></li>
										<li class="nav-item"><a class="nav-link" href="/post/Fact/all">Facts</a></li>
									</ul>
								 
								<li class="nav-item"><a class="nav-link contact" href="/contact">CONTACT</a></li>

								<li class="nav-item"><a class="nav-link" href="/sign-out">LOGOUT</a></li>

							</ul>
							<ul class="nav navbar-nav navbar-right">
								<li class="nav-item"><a href="#" class="search"><i class="lnr lnr-magnifier" title="Search for a user by their username"></i></a></li>
							</ul>
						{% else %}
							<!-- If not a user -->
							<ul class="nav navbar-nav menu_nav ml-auto">
								 
								<li class="nav-item"><a class="nav-link" href="/sign-up">REGISTER</a></li>

								<li class="nav-item"><a class="nav-link" href="/sign-in">LOG IN</a></li>

								<li class="nav-item"><a class="nav-link contact" href="/contact">CONTACT</a></li>
							</ul>
						{% endif %}

					</div> 
				</div>
        	</nav>
        	<ul class="messagelist">
        		<li style="display: none;" class="dacMsg"></li>
        	</ul>
        	{% if messages %}
        		<ul class="messagelist">
        			{% for message in messages %}
        				<li{% if message.tags %} class="{{message.tags}}" {% endif %}>
        					{{message}}
        				</li>
        			{% endfor %}
        		</ul>
        	{% endif %}

        </div>
    </header>


    <!--================Header Menu Area =================-->

    {% block content %}

    {% endblock %}
    


    <!--================ start footer Area  =================-->	
	<footer class="footer-area">
	<div class="container">
	    <div class="row">
	        <div class="col-lg-3  col-md-6 col-sm-6">
	            <div class="single-footer-widget">
	                <h6 class="footer_title">About Us</h6>
	                <p>Flick is an idea to give opportunity to read and publish jokes, quotes, motivational text, puzzle and facts. You get to follow a flick user whose post usually have your attention to get a notification when they release a new post. Flick is an idea of Ganiu Ibrahim and was developed by him.</p>
	            </div>
	        </div>
	        <!-- <div class="col-lg-4 col-md-6 col-sm-6">
	            <div class="single-footer-widget">
	                <h6 class="footer_title">Newsletter</h6>
	                <p>Stay updated with our latest trends</p>		
	                <div id="mc_embed_signup">
	                    <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="subscribe_form relative">
	                        <div class="input-group d-flex flex-row">
	                            <input name="EMAIL" placeholder="Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email Address '" required="" type="email">
	                            <button class="btn sub-btn"><span class="lnr lnr-arrow-right"></span></button>		
	                        </div>									
	                        <div class="mt-10 info"></div>
	                    </form>
	                </div>
	            </div>
	        </div>
	        <div class="col-lg-3 col-md-6 col-sm-6">
	            <div class="single-footer-widget instafeed">
	                <h6 class="footer_title">Instagram Feed</h6>
	                <ul class="list instafeed d-flex flex-wrap">
	                    <li><img src="{% static '/img/instagram/Image-01.jpg' %}" alt=""></li>
                        <li><img src="{% static '/img/instagram/Image-02.jpg' %}" alt=""></li>
                        <li><img src="{% static '/img/instagram/Image-03.jpg' %}" alt=""></li>
                        <li><img src="{% static '/img/instagram/Image-04.jpg' %}" alt=""></li>
                        <li><img src="{% static '/img/instagram/Image-05.jpg' %}" alt=""></li>
                        <li><img src="{% static '/img/instagram/Image-06.jpg' %}" alt=""></li>
                        <li><img src="{% static '/img/instagram/Image-07.jpg' %}" alt=""></li>
                        <li><img src="{% static '/img/instagram/Image-08.jpg' %}" alt=""></li>
	                </ul>
	            </div>
	        </div>	
	        <div class="col-lg-2 col-md-6 col-sm-6">
	            <div class="single-footer-widget f_social_wd">
	                <h6 class="footer_title">Follow Us</h6>
	                <p>Let us be social</p>
	                <div class="f_social">
	                	<a href="#"><i class="fa fa-facebook"></i></a>
						<a href="#"><i class="fa fa-twitter"></i></a>
						<a href="#"><i class="fa fa-dribbble"></i></a>
						<a href="#"><i class="fa fa-behance"></i></a>
	                </div>
	            </div>
	        </div> -->						
	    </div>
	    <div class="row footer-bottom d-flex justify-content-between align-items-center">
	        <p class="col-lg-12 footer-text text-center"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
	Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Flick</p>
	    </div>
	</div>
	</footer>


	<!-- Notification panel -->
	{% if request.user.is_authenticated %}
		{% if title != 'Notifications' %}
			<div class="not_panel">
				<div class="title_region">
					<h4 class="not_title">Notifications {% if user.numofnewnote %}<img src="{% static 'index/img/notification/newnote.png' %}" class="notImg"> <sup class="notNum">{{user.numofnewnote}}</sup> {% else %}<img src="{% static 'index/img/notification/nonote.png' %}" class="notImg">{% endif %}</h4>
				</div>
				<div id="not_content" class="hide">
					{% if notification %}
				    	<ul>
				    		{% for not in notification %}
					    		<a href="{{not.url}}">
						    		<li style="list-style-image: url('/static/index/img/notification/{{not.img}}')">
						    			 {{not.message}} <br><span class="small"> {{not.date}}</span>
						    		</li>
					    		</a>
				    		{% endfor %}
				    	</ul>
			    	{% else %}
			    		<h4>No notification</h4>
			    	{% endif %}
			    	<a href="/notification" class="but_expand"><span class="seemore">See More</span></a>
		    	</div>
		    </div>
	    {% endif %}
    {% endif %}
    <!--================ End footer Area  =================-->



	<!-- <script src="vendors/flipclock/timer.js"></script> -->

	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="{% static '/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static '/js/popper.js' %}"></script>
	<script src="{% static '/js/bootstrap.min.js' %}"></script>
	<script src="{% static '/js/stellar.js' %}"></script>
	<script src="{% static '/vendors/lightbox/simpleLightbox.min.js' %}"></script>
	<script src="{% static '/vendors/nice-select/js/jquery.nice-select.min.js' %}"></script>
	<script src="{% static '/vendors/isotope/imagesloaded.pkgd.min.js' %}"></script>
	<script src="{% static '/vendors/isotope/isotope-min.js' %}"></script>
	<script src="{% static '/vendors/owl-carousel/owl.carousel.min.js' %}"></script>
	<script src="{% static '/js/jquery.ajaxchimp.min.js' %}"></script>
	<script src="{% static '/js/mail-script.js' %}"></script>
	<script src="{% static '/vendors/jquery-ui/jquery-ui.js' %}"></script>
	<script src="{% static '/vendors/counter-up/jquery.waypoints.min.js' %}"></script>
	<script src="{% static '/vendors/counter-up/jquery.counterup.js' %}"></script>
	<script src="{% static '/js/theme.js' %}"></script>
	<script src="{% static '/js/mail-script.js' %}"></script>
	<script src="{% static 'index/js/dac.js' %}"></script>

	<script src="{% static 'index/js/mustache.js' %}"></script>
	<script src="{% static 'index/js/realtime.js' %}"></script>

	<script type="text/javascript">
		$('document').ready(function(){
			// Script to hide the message render after 5 seconds
			setTimeout(function(){
				$('.messagelist').css('display', 'none')
			}, 5000)

			// Script to toggle the notification panel
			$('.not_panel .title_region').on('click', function(){
				$('#not_content').toggleClass('hide')
			})


			$('.title_region').on('click', function(){
				if( $('.not_title img').attr('src')=='/static/index/img/notification/newnote.png' ){
					$.ajax({
						url: '/api/checknotification',
						success: function(data){
							console.log('Data returned!')
							console.log(data)
						}
					})
					$('.notImg').attr('src', '/static/index/img/notification/nonote.png')
					$('.notNum').text(0)
				}
			})
		})
	</script>
</body> 
</html>

index/templates/index/home.html
{% extends "index/base.html" %}


{% load static %}

{% block content %}
	<style type="text/css">
		.img-fluid{
			float: right;
		}
		.f_p_item h4{
			color: white;
		}
		.f_p_item h4:hover{
			color: blue;
		}
	</style>
	 
	<!--================Home Banner Area =================-->
	<section class="home_banner_area">
	    <div class="banner_inner d-flex align-items-center">
			<div class="container">
				<div class="banner_content row">
					<div class="col-lg-5">
						<h3>Stay motivated and protected day by day!</h3>
						<p>People often say that motivation doesn't last. Well, neither does bathing - that is why we recommend it daily.</p>
					</div>
					<div class="col-lg-7">
						<div class="halemet_img">
							<img src="{% static 'index/img/banner/protection.png' %}" alt="">
						</div>
					</div>
				</div>
			</div>
	    </div>
	</section>
	<!--================End Home Banner Area =================-->

	<!--================Feature Product Area =================-->
	{% if Quoteoftheday %}
		<section class="feature_product_area">
			<div class="main_box">
				<div class="container">
					<br><br><br>
					<div class="row hot_product_inner">
						<div class="col-lg-6">
							<div class="hot_p_item">
								<img class="img-fluid" src="{% static 'index/img/product/hot-product/hot-p-1.png' %}" alt="hello">
								<div class="product_text">
									<h4>Lover of the <br />Dopest Jokes?</h4>
									<a href="/post/Joke/all">CHECK IT OUT</a>
								</div>
							</div>
						</div>
						<div class="col-lg-6">
							<div class="hot_p_item">
								<img class="img-fluid" src="{% static 'index/img/product/hot-product/hot-p-2.png' %}" alt="">
								<div class="product_text">
									<h4>Die hard fan <br />of Quotes?</h4>
									<a href="/post/Quote/all">CHECK IT OUT</a>
								</div>
							</div>
						</div>
					</div>
					<div class="feature_product_inner">
						<div class="main_title">
							<h2>Quotes of the day</h2>
							<p>Mind blowing.</p>
						</div>
						<div class="feature_p_slider owl-carousel">
							{% for quote in Quoteoftheday %}
								<div class="item">
									<div class="f_p_item">
										<div class="f_p_img post_height" style="background: url('static/index/img/background/{{quote.post.background}}');">
											<h4 class="white">{{quote.post.body}}</h4>
											<div class="p_icon">
												<a href="/post/{{quote.post.pk}}">More</a>
												<!-- <a href="#"><i class="lnr lnr-cart"></i></a> -->
												<!-- <a href="#" id="heartbreak"><i class="fa fa-heart fa-stack-1x"></i><i class="fa fa-bolt fa-stack-1x fa-inverse"></i></a> -->
											</div>
										</div>
										<a href="#"><h4>By {{quote.post.user.username}}</h4></a>
										<h5> <strong><i class="lnr lnr-heart"></i> {{quote.post.view_set.count}}</strong> </h5>
									</div>
								</div>
							{% endfor %}
							<h3></h3>
						</div>
					</div>
				</div>
			</div>
		</section>
	{% endif %}

	{% if Motivationoftheday %}
		<section class="feature_product_area">
			<div class="main_box">
				<div class="container">
					<div class="feature_product_inner">
						<div class="main_title">
							<h2>Motivation of the day</h2>
							<p>Mind blowing.</p>
						</div>
						<div class="feature_p_slider owl-carousel">
							{% for motive in Motivationoftheday %}
								<div class="item">
									<div class="f_p_item">
										<div class="f_p_img post_height2" style="background: url('static/index/img/background/{{motive.post.background}}');">
											<!-- <img class="/img-fluid" src="{% static '/img/product/feature-product/f-p-1.jpg' %}" alt=""> -->
											<h4 class="white">{{motive.post.body}}</h4>
											<div class="p_icon">
												<a href="/post/{{motive.post.id}}">More</a>

												<!-- <i class="lnr lnr-heart"></i> -->
												
												<!-- <a href="#"><i class="lnr lnr-cart"></i></a> -->
												<!-- <a href="#" id="heartbreak"><i class="fa fa-heart fa-stack-1x"></i><i class="fa fa-bolt fa-stack-1x fa-inverse"></i></a> -->
											</div>
										</div>
										<a href="/profile/{{motive.post.user.username}}"><h4>By {{motive.post.user.username}}</h4></a>
										<h5> <strong><i class="lnr lnr-heart"></i> {{motive.post.view_set.count}}</strong> </h5>
									</div>
								</div>
							{% endfor %}
							<h4></h4>
						</div>
					</div>
				</div>
			</div>
		</section>
	{% endif %}
	<!--================End Feature Product Area =================-->

	<!-- displays If visit is a registed user -->
	<!--================Feature Product Area =================-->
	{% if Jokeoftheday %}
		<section class="feature_product_area">
			<div class="main_box">
				<div class="container">
					<div class="feature_product_inner">
						<div class="main_title">
							<h2>Jokes of the day.</h2>
							<p>Mind blowing.</p>
						</div>
						<div class="feature_p_slider owl-carousel">
							{% for joke in Jokeoftheday %}
								<div class="item">
									<div class="f_p_item">
										<div class="f_p_img post_height" style="background: url('static/index/img/background/{{joke.post.background}}');">
											<h4 class="white">{{joke.post.body}}</h4>
											<div class="p_icon">
												<a href="/post/{{joke.post.pk}}">More</a>
												<!-- <a href="#"><i class="lnr lnr-cart"></i></a> -->
												<!-- <a href="#" id="heartbreak"><i class="fa fa-heart fa-stack-1x"></i><i class="fa fa-bolt fa-stack-1x fa-inverse"></i></a> -->
											</div>
										</div>
										<a href="/profile/{{joke.post.user.username}}"><h4>By {{joke.post.user.username}}</h4></a>
										<h5> <strong><i class="lnr lnr-heart"></i> {{joke.post.view_set.count}}</strong> </h5>
									</div>
								</div>
							{% endfor %}
							<h4></h4>
						</div>
					</div>
				</div>
			</div>
		</section>
	{% endif %}
	<!--================End Feature Product Area =================-->


{% endblock %}

index/templates/index/notification.html
{% extends "index/base.html" %}


{% load static %}

{% block content %}

	<section class="banner_area">
		<div class="banner_inner d-flex align-items-center">
			<div class="container">
				<div class="banner_content text-center">
					<h2><img src="{% static 'index/img/banner/not.png' %}">Notifications</h2>
					<div class="page_link">
						<a href="/">Home</a>
						<a href="/notification">Notifications</a>
					</div>
				</div>
			</div>
		</div>
	</section>
	
	<style type="text/css">
		.not_nav li{
			border-radius: 3px;
			margin: 5px 0px;
			font-size: 16px;
			padding: 10px 5px 10px 10px;
		}
		.not_nav:hover{
			background: #e6e6fa;
		}
	</style>

	<div class="not_space">
		{% if user.notification_set.count %}
			<div class="each_not">
				<ul>
					{% for not in notifications %}
						<a href="{{not.url}}" class="not_nav">
							<li style="list-style-image: url('/static/index/img/notification/{{not.img}}')" class="not_nav">
								 {{not.message}} <br><span class="small"> {{not.date}}</span>
							</li>
						</a>
						<!--  Jan. 23, 2019 -->
					{% endfor %}
				</ul>
			</div>
		{% else %}
			<h4>No notification</h4>
		{% endif %}
	</div>
	
{% endblock %}